"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const morgan_1 = __importDefault(require("morgan"));
const helmet_1 = __importDefault(require("helmet"));
const cors_1 = __importDefault(require("cors"));
const apollo_server_express_1 = require("apollo-server-express");
const resolvers_1 = require("./graphql/resolvers");
const schema_1 = require("./graphql/schema");
const app = express_1.default();
app.use(helmet_1.default());
app.use(morgan_1.default('dev'));
app.use(cors_1.default());
app.use(express_1.default.urlencoded({ extended: true }));
const apolloServer = new apollo_server_express_1.ApolloServer({ typeDefs: schema_1.typeDefs, resolvers: resolvers_1.resolvers });
apolloServer.applyMiddleware({ app, path: "/graphql" });
const port = process.env.PORT || 5000;
app.listen(port, () => console.log(`\nGraphQL Server running on ---> http://localhost:${port}/graphql\n`));
